apiVersion: v1
kind: Secret
metadata:
    name: payment-secret
type: Opaque
data:
    BANK_API: ENC[AES256_GCM,data:o7NzvSss0AMQ7FJx3xPGVJuA/wLWzvCo,iv:63iuWVZLYPHuoD2gsPoLefMs8t901SBBxKatJ+LmAfA=,tag:027mmGmSVZXwqiv4eZi/7w==,type:str]
    API_URL: ENC[AES256_GCM,data:hsGM2lZgF2NCccjGhyDcE0RrgkQfCCMWohlWabuh3Rg=,iv:lwquKqVIHCiwyL9C1uoaQwh/OuS7R8ok+u1EuEjh4C4=,tag:6CCtTCtvLBufXrxHcIed9w==,type:str]
sops:
    age:
        - recipient: age1d6hjvl5l3884tn9k58wx6nf36led9853xfgeyjv06sxwzfpjkyjsm26t70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU282dWxGbU1tNGdXamlM
            VkZieU1MSnZnLzlBcSs1WkQvSUxIMHFlZUNNCit6dGk3SHcxVnFNek1VbGRXS0Yx
            MHJhd1hENzVPZDB6NEdJSk9tWVlXZXcKLS0tIDZJYmdGRHE1RjNmRkxtZldBMGlY
            RXloNE0ydnI3M3JsbWhSMzZhQ2ZYMVkKmP+mPc3uPsWC0Dbg5G7tFTUqUViSSnP1
            1Id0IaGHde9wLBM1r3FHhbpckxTTDyrzMkPzmoV50vQuduk+XqFZpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-25T18:54:59Z"
    mac: ENC[AES256_GCM,data:zEbNvTQDy0dUKYGTmKaO21uZndzg582ipD6NYBHurByt0EIk3cNpzdbExLmE6ATFd1PfWnGZTKSlc4MAWDgVck09rQU7Nwfsx3sW3pFiAYGQLuVNpkRzZXf9EO3/Wl1M+547zN8MMRBFbnQyHyzCdM13HNAGjypYVKBH4vXMxzQ=,iv:jIccjuwJipQpFwe/3VwveDOc6IeRAsoqvj+HMtCmCBY=,tag:QEYnqemOdj678vD55ytXnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
