apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-services
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-services
  template:
    metadata:
      labels:
        app: user-services
    spec:
      containers:
      - name: user-services
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80